/* constructors + drivers data*/

USE Formula1db;

INSERT INTO constructors (TeamID, CountryID, teamName, headquarters, principal, engineSupplier, startYear, constructorTitles, wins, poles, fastestLaps) VALUES
(1, 185, 'Mercedes-AMG Petronas Formula One Team', 'Brackley', 'Toto Wolff', 'Mercedes', '2010-01-01', 8, 116, 129, 96),
(2, 82, 'Scuderia Ferrari', 'Maranello', 'Frédéric Vasseur', 'Ferrari', '1950-01-01', 16, 244, 249, 260),
(3, 185, 'Oracle Red Bull Racing', 'Milton Keynes', 'Christian Horner', 'Honda RBPT', '1997-01-01', 6, 115, 97, 96),
(4, 185, 'McLaren Formula 1 Team', 'Woking', 'Zak Brown', 'Mercedes', '1966-01-01', 8, 183, 156, 165),
(5, 185, 'Aston Martin Aramco F1 Team', 'Silverstone', 'Mike Krack', 'Mercedes', '2018-01-01', 0, 1, 1, 1),
(6, 185, 'Alpine F1 Team', 'Enstone', 'Bruno Famin', 'Renault', '1986-01-01', 2, 1, 20, 15),
(7, 82, 'Visa Cash App RB Formula One Team', 'Faenza', 'Laurent Mekies', 'Honda', '1985-01-01', 0, 2, 1, 3),
(8, 168, 'Stake F1 Team Kick Sauber', 'Hinwil', 'Alessandro Alunni Bravi', 'Ferrari', '1993-01-01', 0, 1, 1, 7),
(9, 186, 'MoneyGram Haas F1 Team', 'Kannapolis', 'Ayao Komatsu', 'Ferrari', '2016-01-01', 0, 4, 1, 2),
(10, 185, 'Williams Racing', 'Grove', 'James Vowles', 'Mercedes', '1978-01-01', 9, 114, 128, 133),
(11, 168, 'Alfa Romeo Racing', 'Hinwil', 'Frederic Vasseur', 'Ferrari', '1950-01-01', 0, 0, 0, 0),
(12, 82, 'AlphaTauri', 'Faenza', 'Franz Tost', 'Honda', '2006-01-01', 1, 2, 1, 2),
(13, 185, 'Benetton Formula Ltd.', 'Enstone', 'Flavio Briatore', 'Ford', '1986-01-01', 2, 27, 15, 22),
(14, 185, 'Brawn GP Formula One Team', 'Brackley', 'Ross Brawn', 'Mercedes', '2009-01-01', 1, 8, 5, 5),
(15, 185, 'BRM', 'Bourne', 'Alfred Owen', 'BRM', '1951-01-01', 1, 17, 13, 15),
(16, 185, 'Caterham F1 Team', 'Leafield', 'Cyril Abiteboul', 'Renault', '2010-01-01', 0, 0, 0, 0),
(17, 185, 'Lotus Racing', 'Hingham', 'Tony Fernandes', 'Cosworth', '2010-01-01', 0, 0, 0, 0),
(18, 185, 'Team Lotus', 'Hethel', 'Colin Chapman', 'Lotus', '1958-01-01', 7, 79, 107, 75),
(19, 163, 'HRT Formula 1 Team', 'Madrid', 'Colin Kolles', 'Cosworth', '2010-01-01', 0, 0, 0, 0),
(20, 185, 'Honda Racing F1 Team', 'Brackley', 'Ross Brawn', 'Honda', '2006-01-01', 0, 0, 0, 0),
(21, 185, 'Jaguar Racing', 'Milton Keynes', 'Tony Purnell', 'Ford', '2000-01-01', 0, 0, 0, 0),
(22, 185, 'Jordan Grand Prix', 'Silverstone', 'Eddie Jordan', 'Peugeot', '1991-01-01', 0, 4, 2, 4),
(23, 60, 'Ligier', 'Viry-Chatillon', 'Guy Ligier', 'Ligier', '1976-01-01', 0, 9, 9, 9),
(24, 185, 'Marussia F1 Team', 'Banbury', 'John Booth', 'Cosworth', '2010-01-01', 0, 0, 0, 0),
(25, 185, 'Spyker F1', 'Silverstone', 'Michiel Mol', 'Ferrari', '2007-01-01', 0, 0, 0, 0),
(26, 185, 'Virgin Racing', 'Banbury', 'John Booth', 'Cosworth', '2010-01-01', 0, 0, 0, 0),
(27, 168, 'Sauber', 'Hinwil', 'Frédéric Vasseur', 'Ferrari', '1993-01-01', 0, 1, 1, 1),
(28, 185, 'Shadow Racing Cars', 'Northamptonshire', 'Don Nichols', 'Shadow', '1973-01-01', 0, 0, 0, 0),
(29, 185, 'Stewart Grand Prix', 'Milton Keynes', 'Paul Stewart', 'Ford', '1997-01-01', 0, 1, 1, 1),
(30, 84, 'Super Aguri F1', 'Tokyo', 'Aguri Suzuki', 'Honda', '2006-01-01', 0, 0, 0, 0),
(31, 185, 'Tyrrell Racing Organisation', 'Ockham', 'Ken Tyrrell', 'Cosworth', '1968-01-01', 1, 23, 19, 16),
(32, 64, 'Veritas', 'Nuremberg', 'Georg Meier', 'Veritas', '1950-01-01', 0, 0, 0, 0);

-- all fields
SELECT * FROM constructors;

-- just constructor name and location
SELECT c.teamName, c.headquarters, co.countryName
FROM constructors c
JOIN countries co ON c.CountryFK = co.CountryID;

-- pull all information from constructors table
SELECT 
    c.TeamID,
    co.countryName AS CountryName,
    c.teamName,
    c.headquarters,
    c.principal,
    c.engineSupplier,
    c.startYear,
    c.constructorTitles,
    c.wins,
    c.poles,
    c.fastestLaps
FROM 
    constructors c
JOIN 
    countries co ON c.CountryFK = co.CountryID
ORDER BY 
    c.TeamID 
OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY; 



/* Drivers Table */
INSERT INTO drivers (DriverID, TeamID, CountryID, firstName, lastName, dateOfBirth, born, helmutColour, number)
VALUES
	(1, 1, 185, 'Lewis', 'Hamilton', '1985-01-07', 'Stevenage', 'Purple', 44),
	(2,  1, 185, 'George', 'Russell', '1998-02-15', 'Kings Lynn', 'Blue', 63),
	(3, 3, 17, 'Max', 'Verstappen', '1997-09-30', 'Hasselt', 'White', 1),
	(4, 3, 111, 'Sergio','Pérez', '1990-01-26', 'Guadalajara', 'Blue', 11),
	(5, 2, 114, 'Charles', 'Leclerc', '1997-10-16', 'Monte Carlo', 'Red', 16),
	(6, 8, 59, 'Valtteri', 'Bottas', '1989-08-28', 'Nastola', 'Blue', 77),
	(7, 7, 9, 'Daniel', 'Ricciardo', '1989-07-01', 'Perth', 'Silver', 3),
	(8, 4, 185, 'Lando', 'Norris', '1999-11-13', 'Bristold', 'Green', 4),
	(9, 2, 163, 'Carlos', 'Sainz', '1994-09-01', 'Madrid', 'Red', 55),
	(10, 6, 60, 'Esteban', 'Ocon', '1996-09-17', 'Évreux', 'Black', 31),
	(11, 4, 9, 'Oscar', 'Piastri', '2001-04-06', 'Melbourne', 'Blue',  81),
	(12, 6, 60, 'Pierre', 'Gasly', '1996-02-07', 'Rouen', 'Orange', 10),
	(13, 5, 32, 'Lance', 'Stroll', '1998-10-29', 'Montreal', 'Green', 18),
	(14, 7, 85, 'Yuki', 'Tsunoda', '2000-05-11', 'Sagamihara', 'Blue', 22),
	(15, 9, 46, 'Kevin', 'Magnussen', '1992-10-05', 'Roskilde', 'White', 20),
	(16, 10, 186, 'Logan', 'Sargeant', '2000-12-31', 'Fort Lauderdale', 'Blue', 2),
	(17, 8, 36, 'Zhou', 'Guanyu', '1999-05-20', 'Shanghai', 'Purple', 24),
	(18, 10, 185, 'Alexander', 'Albon', '1996-03-23', 'London', 'Pink', 23),
	(19, 9, 64, 'Niko', 'Hulkenberg', '1987-08-19', 'Emmerich am Rhein', 'Silver', 27),
	(20, 5, 163, 'Fernando', 'Alonso', '1981-07-29', 'Oviedo', 'Yellow', 14),
	(21, 9, 185, 'Oliver', 'Bearman', '2005-05-08', 'Chelmsford', 'Blue', 10),
	(23, 10, 7, 'Franco', 'Colapinto', '2003-05-27', 'Buenos Aires', 'White', 43),
	(24, 7, 124, 'Liam', 'Lawson','2002-02-11', 'Hastings,', 'White', 30),
	(25, NULL, NULL, 'Nino', 'Farina', NULL, NULL, NULL, NULL),
	(26, NULL, NULL, 'Juan Manuel', 'Fangio', NULL, NULL, NULL, NULL),
	(27, NULL, NULL, 'Luigi', 'Fagioli', NULL, NULL, NULL, NULL),
	(28, NULL, NULL, 'Carlo', 'Abate', NULL, NULL, NULL, NULL),	
	(29, NULL, NULL, 'George', 'Abecassis', NULL, NULL, NULL, NULL),
	(30, NULL, NULL, 'Kenny', 'Acheson', NULL, NULL, NULL, NULL),	 
	(31, NULL, NULL, 'Andrea de', 'Adamich', NULL, NULL, NULL, NULL),	
	(32, NULL, NULL, 'Philippe', 'Adams', NULL, NULL, NULL, NULL),	
	(33, NULL, NULL, 'Walt', 'Ader', NULL, NULL, NULL, NULL),	 
	(34, NULL, NULL, 'Kurt', 'Adolff', NULL, NULL, NULL, NULL),	 
	(35, NULL, NULL, 'Fred', 'Agabashian', NULL, NULL, NULL, NULL),	
	(36, NULL, NULL, 'Kurt', 'Ahrens, Jr.', NULL, NULL, NULL, NULL),
	(37, NULL, NULL, 'Christijan', 'Albers', NULL, NULL, NULL, NULL),
	(38, NULL, NULL, 'Michele', 'Alboreto', NULL, NULL, NULL, NULL),
	(39, NULL, NULL, 'Jean', 'Alesi', NULL, NULL, NULL, NULL),
	(40, NULL, NULL, 'Jaimel', 'Alguersuari', NULL, NULL, NULL, NULL),
	(41, NULL, NULL, 'Philippe', 'Alliot', NULL, NULL, NULL, NULL),
	(42, NULL, NULL, 'Cliff', 'Allison', NULL, NULL, NULL, NULL),
	(43, NULL, NULL, 'Giovanna', 'Amati', NULL, NULL, NULL, NULL),
	(44, NULL, NULL, 'George', 'Amick', NULL, NULL, NULL, NULL),
	(45, NULL, NULL, 'Red', 'Amick', NULL, NULL, NULL, NULL),
	(46, NULL, NULL, 'Chris', 'Amon', NULL, NULL, NULL, NULL),
	(47, NULL, NULL, 'Bob', 'Anderson', NULL, NULL, NULL, NULL),
	(48, NULL, NULL, 'Conny', 'Andersson', NULL, NULL, NULL, NULL),
	(49, NULL, NULL, 'Mario', 'Andretti', NULL, NULL, NULL, NULL),
	(50, NULL, NULL, 'Michael', 'Andretti', NULL, NULL, NULL, NULL),
	(51, NULL, NULL, 'Keith', 'Andrews', NULL, NULL, NULL, NULL),
	(52, NULL, NULL, 'Elio de', 'Angelis', NULL, NULL, NULL, NULL),
	(53, NULL, NULL, 'Marco', 'Apicella', NULL, NULL, NULL, NULL),
	(54, NULL, NULL, 'Mário de', 'Araújo Cabral', NULL, NULL, NULL, NULL),
	(55, NULL, NULL, 'Frank', 'Armi', NULL, NULL, NULL, NULL),
	(56, NULL, NULL, 'Chuck', 'Arnold', NULL, NULL, NULL, NULL),
	(57, NULL, NULL, 'René', 'Arnoux', NULL, NULL, NULL, NULL),
	(58, NULL, NULL, 'Peter', 'Arundell', NULL, NULL, NULL, NULL),
	(59, NULL, NULL, 'Alberto', 'Ascari', NULL, NULL, NULL, NULL),
	(60, NULL, NULL, 'Peter', 'Ashdown', NULL, NULL, NULL, NULL),
	(61, NULL, NULL, 'Ian', 'Ashley', NULL, NULL, NULL, NULL),
	(62, NULL, NULL, 'Gerry', 'Ashmore', NULL, NULL, NULL, NULL),
	(63, NULL, NULL, 'Bill', 'Aston', NULL, NULL, NULL, NULL),
	(64, NULL, NULL, 'Richard', 'Attwood', NULL, NULL, NULL, NULL),
	(65, NULL, NULL, 'Manny', 'Ayulo', NULL, NULL, NULL, NULL),
	(66, NULL, NULL, 'Luca', 'Badoer', NULL, NULL, NULL, NULL),
	(67, NULL, NULL, 'Giancarlo', 'Baghetti', NULL, NULL, NULL, NULL),
	(68, NULL, NULL, 'Julian', 'Bailey', NULL, NULL, NULL, NULL),
	(69, NULL, NULL, 'Mauro', 'Baldi', NULL, NULL, NULL, NULL),
	(70, NULL, NULL, 'Bobby', 'Ball', NULL, NULL, NULL, NULL),
	(71, NULL, NULL, 'Marcel', 'Balsa', NULL, NULL, NULL, NULL),
	(72, NULL, NULL, 'Lorenzo', 'Bandini', NULL, NULL, NULL, NULL),
	(73, NULL, NULL, 'Henry', 'Banks', NULL, NULL, NULL, NULL),
	(74, NULL, NULL, 'Fabrizio', 'Barbazza', NULL, NULL, NULL, NULL),
	(75, NULL, NULL, 'John', 'Barber', NULL, NULL, NULL, NULL),
	(76, NULL, NULL, 'Skip', 'Barber', NULL, NULL, NULL, NULL),
	(77, NULL, NULL, 'Paolo', 'Barilla', NULL, NULL, NULL, NULL),
	(78, NULL, NULL, 'Rubens', 'Barrichello', NULL, NULL, NULL, NULL),
	(79, NULL, NULL, 'Michael', 'Bartels', NULL, NULL, NULL, NULL),
	(80, NULL, NULL, 'Edgar', 'Barth', NULL, NULL, NULL, NULL),
	(81, NULL, NULL, 'Giorgio', 'Bassi', NULL, NULL, NULL, NULL),
	(82, NULL, NULL, 'Erwin', 'Bauer', NULL, NULL, NULL, NULL),
	(83, NULL, NULL, 'Zsolt', 'Baumgartner', NULL, NULL, NULL, NULL),
	(84, NULL, NULL, 'Élie', 'Bayol', NULL, NULL, NULL, NULL),
	(85, NULL, NULL, 'Don', 'Beauman', NULL, NULL, NULL, NULL),
	(86, NULL, NULL, 'Karl-Günther', 'Bechem', NULL, NULL, NULL, NULL),
	(87, NULL, NULL, 'Jean', 'Behra', NULL, NULL, NULL, NULL),
	(88, NULL, NULL, 'Derek', 'Bell', NULL, NULL, NULL, NULL),
	(89, NULL, NULL, 'Stefan', 'Bellof', NULL, NULL, NULL, NULL),
	(90, NULL, NULL, 'Paul', 'Belmondo', NULL, NULL, NULL, NULL),
	(91, NULL, NULL, 'Tom', 'Belsø', NULL, NULL, NULL, NULL),
	(92, NULL, NULL, 'Jean-Pierre', 'Beltoise', NULL, NULL, NULL, NULL),
	(93, NULL, NULL, 'Olivier', 'Beretta', NULL, NULL, NULL, NULL),
	(94, NULL, NULL, 'Allen', 'Berg', NULL, NULL, NULL, NULL),
	(95, NULL, NULL, 'Georges', 'Berger', NULL, NULL, NULL, NULL),
	(96, NULL, NULL, 'Gerhard', 'Berger', NULL, NULL, NULL, NULL),
	(97, NULL, NULL, 'Éric', 'Bernard', NULL, NULL, NULL, NULL),
	(98, NULL, NULL, 'Enrique', 'Bernoldi', NULL, NULL, NULL, NULL),
	(99, NULL, NULL, 'Enrico', 'Bertaggia', NULL, NULL, NULL, NULL),
	(100, NULL, NULL, 'Tony', 'Bettenhausen', NULL, NULL, NULL, NULL),
	(101, NULL, NULL, 'Mike', 'Beuttler', NULL, NULL, NULL, NULL),
	(102, NULL, NULL, 'Birabongse', 'Bhanudej', NULL, NULL, NULL, NULL),
	(103, NULL, NULL, 'Jules', 'Bianchi', NULL, NULL, NULL, NULL),
	(104, NULL, NULL, 'Lucien', 'Bianchi', NULL, NULL, NULL, NULL),
	(105, NULL, NULL, 'Gino', 'Bianco', NULL, NULL, NULL, NULL),
	(106, NULL, NULL, 'Hans', 'Binder', NULL, NULL, NULL, NULL),
	(107, NULL, NULL, 'Clemente', 'Biondetti', NULL, NULL, NULL, NULL),
	(108, NULL, NULL, 'Pablo', 'Birger', NULL, NULL, NULL, NULL),
	(109, NULL, NULL, 'Art', 'Bisch', NULL, NULL, NULL, NULL),
	(110, NULL, NULL, 'Harry', 'Blanchard', NULL, NULL, NULL, NULL),
	(111, NULL, NULL, 'Michael', 'Bleekemolen', NULL, NULL, NULL, NULL),
	(112, NULL, NULL, 'Alex', 'Blignaut', NULL, NULL, NULL, NULL),
	(113, NULL, NULL, 'Trevor', 'Blokdyk', NULL, NULL, NULL, NULL),
	(114, NULL, NULL, 'Mark', 'Blundell', NULL, NULL, NULL, NULL),
	(115, NULL, NULL, 'Raul', 'Boesel', NULL, NULL, NULL, NULL),
	(116, NULL, NULL, 'Menato', 'Boffa', NULL, NULL, NULL, NULL),
	(117, NULL, NULL, 'Bob', 'Bondurant', NULL, NULL, NULL, NULL),
	(118, NULL, NULL, 'Felice', 'Bonetto', NULL, NULL, NULL, NULL),
	(119, NULL, NULL, 'Jo', 'Bonnier', NULL, NULL, NULL, NULL),
	(120, NULL, NULL, 'Roberto', 'Bonomi', NULL, NULL, NULL, NULL),
	(121, NULL, NULL, 'Juan Manuel', 'Bordeu', NULL, NULL, NULL, NULL),
	(122, NULL, NULL, 'Slim', 'Borgudd', NULL, NULL, NULL, NULL),
	(123, NULL, NULL, 'Luki', 'Botha', NULL, NULL, NULL, NULL),
	(124, NULL, NULL, 'Jean-Christophe', 'Boullion', NULL, NULL, NULL, NULL),
	(125, NULL, NULL, 'Sébastien', 'Bourdais', NULL, NULL, NULL, NULL),
	(126, NULL, NULL, 'Thierry', 'Boutse', NULL, NULL, NULL, NULL),
	(127, NULL, NULL, 'Johnny', 'Boyd', NULL, NULL, NULL, NULL),
	(128, NULL, NULL, 'David', 'Brabham', NULL, NULL, NULL, NULL),
	(129, NULL, NULL, 'Gary', 'Brabham', NULL, NULL, NULL, NULL),
	(130, NULL, NULL, 'Jack', 'Brabham', NULL, NULL, NULL, NULL),
	(131, NULL, NULL, 'Bill', 'Brack', NULL, NULL, NULL, NULL),
	(132, NULL, NULL, 'Ernesto', 'Brambilla', NULL, NULL, NULL, NULL),
	(133, NULL, NULL, 'Vittorio', 'Brambilla', NULL, NULL, NULL, NULL),
	(134, NULL, NULL, 'Toni', 'Branca', NULL, NULL, NULL, NULL),
	(135, NULL, NULL, 'Gianfranco', 'Brancatelli', NULL, NULL, NULL, NULL),
	(136, NULL, NULL, 'Eric', 'Brandon', NULL, NULL, NULL, NULL),
	(137, NULL, NULL, 'Don', 'Branson', NULL, NULL, NULL, NULL),
	(138, NULL, NULL, 'Tom', 'Bridger', NULL, NULL, NULL, NULL),
	(139, NULL, NULL, 'Tony', 'Brise', NULL, NULL, NULL, NULL),
	(140, NULL, NULL, 'Chris', 'Bristow', NULL, NULL, NULL, NULL),
	(141, NULL, NULL, 'Peter', 'Broeker', NULL, NULL, NULL, NULL),
	(142, NULL, NULL, 'Tony', 'Brooks', NULL, NULL, NULL, NULL),
	(143, NULL, NULL, 'Alan', 'Brown', NULL, NULL, NULL, NULL),
	(144, NULL, NULL, 'Walt', 'Brown', NULL, NULL, NULL, NULL),
	(145, NULL, NULL, 'Warwick', 'Brown', NULL, NULL, NULL, NULL),
	(146, NULL, NULL, 'Adolf', 'Brudes', NULL, NULL, NULL, NULL),
	(147, NULL, NULL, 'Martin', 'Brundle', NULL, NULL, NULL, NULL),
	(148, NULL, NULL, 'Gianmaria', 'Bruni', NULL, NULL, NULL, NULL),
	(149, NULL, NULL, 'Jimmy', 'Bryan', NULL, NULL, NULL, NULL),
	(150, NULL, NULL, 'Clemar', 'Bucci', NULL, NULL, NULL, NULL),
	(151, NULL, NULL, 'Ronnie', 'Bucknum', NULL, NULL, NULL, NULL),
	(152, NULL, NULL, 'Ivor', 'Bueb', NULL, NULL, NULL, NULL),
	(153, NULL, NULL, 'Sébastien', 'Buemi', NULL, NULL, NULL, NULL),
	(154, NULL, NULL, 'Luiz', 'Bueno', NULL, NULL, NULL, NULL),
	(155, NULL, NULL, 'Ian', 'Burgess', NULL, NULL, NULL, NULL),
	(156, NULL, NULL, 'Luciano', 'Burti', NULL, NULL, NULL, NULL),
	(157, NULL, NULL, 'Roberto', 'Bussinello', NULL, NULL, NULL, NULL),
	(158, NULL, NULL, 'Jenson', 'Button', NULL, NULL, NULL, NULL),
	(159, NULL, NULL, 'Tommy', 'Byrne', NULL, NULL, NULL, NULL),
	(160, NULL, NULL, 'Giulio', 'Cabianca', NULL, NULL, NULL, NULL),
	(161, NULL, NULL, 'Phil', 'Cade', NULL, NULL, NULL, NULL),
	(162, NULL, NULL, 'Alex', 'Caffi', NULL, NULL, NULL, NULL),
	(163, NULL, NULL, 'John', 'Campbell-Jones', NULL, NULL, NULL, NULL),
	(164, NULL, NULL, 'Adrián', 'Campos', NULL, NULL, NULL, NULL),
	(165, NULL, NULL, 'John', 'Cannon', NULL, NULL, NULL, NULL),
	(166, NULL, NULL, 'Eitel', 'Cantoni', NULL, NULL, NULL, NULL),
	(167, NULL, NULL, 'Bill', 'Cantrell', NULL, NULL, NULL, NULL),
	(168, NULL, NULL, 'Ivan', 'Capelli', NULL, NULL, NULL, NULL),
	(169, NULL, NULL, 'Piero', 'Carini', NULL, NULL, NULL, NULL),
	(170, NULL, NULL, 'Duane', 'Carter', NULL, NULL, NULL, NULL),
	(171, NULL, NULL, 'Eugenio', 'Castellotti', NULL, NULL, NULL, NULL),
	(172, NULL, NULL, 'Johnny', 'Cecotto', NULL, NULL, NULL, NULL),
	(173, NULL, NULL, 'Andrea', 'de Cesaris', NULL, NULL, NULL, NULL),
	(174, NULL, NULL, 'François', 'Cevert', NULL, NULL, NULL, NULL),
	(175, NULL, NULL, 'Eugène', 'Chaboud', NULL, NULL, NULL, NULL),
	(176, NULL, NULL, 'Jay', 'Chamberlain', NULL, NULL, NULL, NULL),
	(177, NULL, NULL, 'Karun', 'Chandhok', NULL, NULL, NULL, NULL),
	(178, NULL, NULL, 'Alain', 'de Changy', NULL, NULL, NULL, NULL),
	(179, NULL, NULL, 'Colin', 'Chapman', NULL, NULL, NULL, NULL),
	(180, NULL, NULL, 'Dave', 'Charlton', NULL, NULL, NULL, NULL),
	(181, NULL, NULL, 'Pedro Matos', 'Chaves', NULL, NULL, NULL, NULL),
	(182, NULL, NULL, 'Bill', 'Cheesbourg', NULL, NULL, NULL, NULL),
	(183, NULL, NULL, 'Eddie', 'Cheever', NULL, NULL, NULL, NULL),
	(184, NULL, NULL, 'Andrea', 'Chiesa', NULL, NULL, NULL, NULL),
	(185, NULL, NULL, 'Max', 'Chilton', NULL, NULL, NULL, NULL),
	(186, NULL, NULL, 'Ettore', 'Chimeri', NULL, NULL, NULL, NULL),
	(187, NULL, NULL, 'Louis', 'Chiron', NULL, NULL, NULL, NULL),
	(188, NULL, NULL, 'Joie', 'Chitwood', NULL, NULL, NULL, NULL),
	(189, NULL, NULL, 'Bob', 'Christie', NULL, NULL, NULL, NULL),
	(190, NULL, NULL, 'Johnny', 'Claes', NULL, NULL, NULL, NULL),
	(191, NULL, NULL, 'David', 'Clapham', NULL, NULL, NULL, NULL),
	(192, NULL, NULL, 'Jim', 'Clark', NULL, NULL, NULL, NULL),
	(193, NULL, NULL, 'Kevin', 'Cogan', NULL, NULL, NULL, NULL),
	(194, NULL, NULL, 'Peter', 'Collins', NULL, NULL, NULL, NULL),
	(195, NULL, NULL, 'Bernard', 'Collomb', NULL, NULL, NULL, NULL),
	(196, NULL, NULL, 'Alberto', 'Colombo', NULL, NULL, NULL, NULL),
	(197, NULL, NULL, 'Érik', 'Comas', NULL, NULL, NULL, NULL),
	(198, NULL, NULL, 'Franco', 'Comotti', NULL, NULL, NULL, NULL),
	(199, NULL, NULL, 'George', 'Connor', NULL, NULL, NULL, NULL),
	(200, NULL, NULL, 'George', 'Constantine', NULL, NULL, NULL, NULL),
	(201, NULL, NULL, 'John', 'Cordts', NULL, NULL, NULL, NULL),
	(202, NULL, NULL, 'David', 'Coulthard', NULL, NULL, NULL, NULL),
	(203, NULL, NULL, 'Piers', 'Courage', NULL, NULL, NULL, NULL),
	(204, NULL, NULL, 'Chris', 'Craft', NULL, NULL, NULL, NULL),
	(205, NULL, NULL, 'Jim', 'Crawford', NULL, NULL, NULL, NULL),
	(206, NULL, NULL, 'Ray', 'Crawford', NULL, NULL, NULL, NULL),
	(207, NULL, NULL, 'Alberto', 'Crespo', NULL, NULL, NULL, NULL),
	(208, NULL, NULL, 'Antonio', 'Creus', NULL, NULL, NULL, NULL),
	(209, NULL, NULL, 'Larry', 'Crockett', NULL, NULL, NULL, NULL),
	(211, NULL, NULL, 'Chuck', 'Daigh', NULL, NULL, NULL, NULL),
	(212, NULL, NULL, 'Yannick', 'Dalmas', NULL, NULL, NULL, NULL),
	(213, NULL, NULL, 'Derek', 'Daly', NULL, NULL, NULL, NULL),
	(214, NULL, NULL, 'Christian', 'Danner', NULL, NULL, NULL, NULL),
	(215, NULL, NULL, 'Jorge', 'Daponte', NULL, NULL, NULL, NULL),
	(216, NULL, NULL, 'Anthony', 'Davidson', NULL, NULL, NULL, NULL),
	(217, NULL, NULL, 'Jimmy', 'Davies', NULL, NULL, NULL, NULL),
	(218, NULL, NULL, 'Colin', 'Davis', NULL, NULL, NULL, NULL),
	(219, NULL, NULL, 'Jimmy', 'Daywalt', NULL, NULL, NULL, NULL),
	(220, NULL, NULL, 'Patrick', 'Depailler', NULL, NULL, NULL, NULL),
	(221, NULL, NULL, 'Pedro', 'Diniz', NULL, NULL, NULL, NULL),
	(222, NULL, NULL, 'Duke', 'Dinsmore', NULL, NULL, NULL, NULL),
	(223, NULL, NULL, 'Frank', 'Dochnal', NULL, NULL, NULL, NULL),
	(224, NULL, NULL, 'José', 'Dolhem', NULL, NULL, NULL, NULL),
	(225, NULL, NULL, 'Martin', 'Donnelly', NULL, NULL, NULL, NULL),
	(226, NULL, NULL, 'Mark', 'Donohue', NULL, NULL, NULL, NULL),
	(227, NULL, NULL, 'Robert', 'Doornbos', NULL, NULL, NULL, NULL),
	(228, NULL, NULL, 'Ken', 'Downing', NULL, NULL, NULL, NULL),
	(229, NULL, NULL, 'Bob', 'Drake', NULL, NULL, NULL, NULL),
	(230, NULL, NULL, 'Paddy', 'Driver', NULL, NULL, NULL, NULL),
	(231, NULL, NULL, 'Piero', 'Drogo', NULL, NULL, NULL, NULL),
	(232, NULL, NULL, 'Bernard de', 'Dryver', NULL, NULL, NULL, NULL),
	(233, NULL, NULL, 'Geoff', 'Duke', NULL, NULL, NULL, NULL),
	(234, NULL, NULL, 'Johnny', 'Dumfries', NULL, NULL, NULL, NULL),
	(235, NULL, NULL, 'Len', 'Duncan', NULL, NULL, NULL, NULL),
	(236, NULL, NULL, 'Piero', 'Dusio', NULL, NULL, NULL, NULL),
	(237, NULL, NULL, 'Jean-Denis', 'Délétraz', NULL, NULL, NULL, NULL),
	(238, NULL, NULL, 'George', 'Eaton', NULL, NULL, NULL, NULL),
	(239, NULL, NULL, 'Bernie', 'Ecclestone', NULL, NULL, NULL, NULL),
	(240, NULL, NULL, 'Don', 'Edmunds', NULL, NULL, NULL, NULL),
	(241, NULL, NULL, 'Guy', 'Edwards', NULL, NULL, NULL, NULL),
	(242, NULL, NULL, 'Vic', 'Elford', NULL, NULL, NULL, NULL),
	(243, NULL, NULL, 'Ed', 'Elisian', NULL, NULL, NULL, NULL),
	(244, NULL, NULL, 'Paul', 'Emery', NULL, NULL, NULL, NULL),
	(245, NULL, NULL, 'Tomáš', 'Enge', NULL, NULL, NULL, NULL),
	(246, NULL, NULL, 'Paul', 'England', NULL, NULL, NULL, NULL),
	(247, NULL, NULL, 'Marcus', 'Ericsson', NULL, NULL, NULL, NULL),
	(248, NULL, NULL, 'Harald', 'Ertl', NULL, NULL, NULL, NULL),
	(249, NULL, NULL, 'Nasif', 'Estéfano', NULL, NULL, NULL, NULL),
	(250, NULL, NULL, 'Bob', 'Evans', NULL, NULL, NULL, NULL),
	(251, NULL, NULL, 'Corrado', 'Fabi', NULL, NULL, NULL, NULL),
	(252, NULL, NULL, 'Teo', 'Fabi', NULL, NULL, NULL, NULL),
	(253, NULL, NULL, 'Pascal', 'Fabre', NULL, NULL, NULL, NULL),
	(254, NULL, NULL, 'Carlo', 'Facetti', NULL, NULL, NULL, NULL),
	(255, NULL, NULL, 'Jack', 'Fairman', NULL, NULL, NULL, NULL),
	(256, NULL, NULL, 'Walt', 'Faulkner', NULL, NULL, NULL, NULL),
	(257, NULL, NULL, 'William', 'Ferguson', NULL, NULL, NULL, NULL),
	(258, NULL, NULL, 'Maria Teresa de', 'Filippis', NULL, NULL, NULL, NULL),
	(259, NULL, NULL, 'Ralph', 'Firman', NULL, NULL, NULL, NULL),
	(260, NULL, NULL, 'Ludwig', 'Fischer', NULL, NULL, NULL, NULL),
	(261, NULL, NULL, 'Rudi', 'Fischer', NULL, NULL, NULL, NULL),
	(262, NULL, NULL, 'Mike', 'Fisher', NULL, NULL, NULL, NULL),
	(263, NULL, NULL, 'Giancarlo', 'Fisichella', NULL, NULL, NULL, NULL),
	(264, NULL, NULL, 'John', 'Fitch', NULL, NULL, NULL, NULL),
	(265, NULL, NULL, 'Christian', 'Fittipaldi', NULL, NULL, NULL, NULL),
	(266, NULL, NULL, 'Emerson', 'Fittipaldi', NULL, NULL, NULL, NULL),
	(267, NULL, NULL, 'Wilson', 'Fittipaldi', NULL, NULL, NULL, NULL),
	(268, NULL, NULL, 'Theo', 'Fitzau', NULL, NULL, NULL, NULL),
	(269, NULL, NULL, 'Pat', 'Flaherty', NULL, NULL, NULL, NULL),
	(270, NULL, NULL, 'Jan', 'Flinterman', NULL, NULL, NULL, NULL),
	(271, NULL, NULL, 'Ron', 'Flockhart', NULL, NULL, NULL, NULL),
	(272, NULL, NULL, 'Myron', 'Fohr', NULL, NULL, NULL, NULL),
	(273, NULL, NULL, 'Gregor', 'Foitek', NULL, NULL, NULL, NULL),
	(274, NULL, NULL, 'George', 'Follmer', NULL, NULL, NULL, NULL),
	(275, NULL, NULL, 'George', 'Fonder', NULL, NULL, NULL, NULL),
	(276, NULL, NULL, 'Norberto', 'Fontana', NULL, NULL, NULL, NULL),
	(277, NULL, NULL, 'Asdrúbal', 'Fontes', NULL, NULL, NULL, NULL),
	(278, NULL, NULL, 'Carl', 'Forberg', NULL, NULL, NULL, NULL),
	(279, NULL, NULL, 'Gene', 'Force', NULL, NULL, NULL, NULL),
	(280, NULL, NULL, 'Franco', 'Forini', NULL, NULL, NULL, NULL),
	(281, NULL, NULL, 'Philip', 'Fotheringham-Parker', NULL, NULL, NULL, NULL),
	(282, NULL, NULL, 'A.J.', 'Foyt', NULL, NULL, NULL, NULL),
	(283, NULL, NULL, 'Giorgio', 'Francia', NULL, NULL, NULL, NULL),
	(284, NULL, NULL, 'Fred', 'Wacker', NULL, NULL, NULL, NULL),
	(285, NULL, NULL, 'Don', 'Freeland', NULL, NULL, NULL, NULL),
	(286, NULL, NULL, 'Heinz-Harald', 'Frentzen', NULL, NULL, NULL, NULL),
	(287, NULL, NULL, 'Patrick', 'Friesacher', NULL, NULL, NULL, NULL),
	(288, NULL, NULL, 'Joe', 'Fry', NULL, NULL, NULL, NULL),
	(289, NULL, NULL, 'Paul', 'Frère', NULL, NULL, NULL, NULL),
	(290, NULL, NULL, 'Hiroshi', 'Fushida', NULL, NULL, NULL, NULL),
	(291, NULL, NULL, 'Beppe', 'Gabbiani', NULL, NULL, NULL, NULL),
	(292, NULL, NULL, 'Bertrand', 'Gachot', NULL, NULL, NULL, NULL),
	(293, NULL, NULL, 'Patrick', 'Gaillard', NULL, NULL, NULL, NULL),
	(294, NULL, NULL, 'Divina', 'Galica', NULL, NULL, NULL, NULL),
	(295, NULL, NULL, 'Nanni', 'Galli', NULL, NULL, NULL, NULL),
	(296, NULL, NULL, 'Fred', 'Gamble', NULL, NULL, NULL, NULL),
	(297, NULL, NULL, 'Howden', 'Ganley', NULL, NULL, NULL, NULL),
	(298, NULL, NULL, 'Giedo van', 'der Garde', NULL, NULL, NULL, NULL),
	(299, NULL, NULL, 'Frank', 'Gardner', NULL, NULL, NULL, NULL),
	(300, NULL, NULL, 'Billy', 'Garrett', NULL, NULL, NULL, NULL),
	(301, NULL, NULL, 'Jo', 'Gartner', NULL, NULL, NULL, NULL),
	(302, NULL, NULL, 'Tony', 'Gaze', NULL, NULL, NULL, NULL),
	(303, NULL, NULL, 'Olivier', 'Gendebien', NULL, NULL, NULL, NULL),
	(304, NULL, NULL, 'Marc', 'Gené', NULL, NULL, NULL, NULL),
	(305, NULL, NULL, 'Elmer', 'George', NULL, NULL, NULL, NULL),
	(306, NULL, NULL, 'Bob', 'Gerard', NULL, NULL, NULL, NULL),
	(307, NULL, NULL, 'Gerino', 'Gerini', NULL, NULL, NULL, NULL),
	(308, NULL, NULL, 'Peter', 'Gethin', NULL, NULL, NULL, NULL),
	(309, NULL, NULL, 'Piercarlo', 'Ghinzani', NULL, NULL, NULL, NULL),
	(310, NULL, NULL, 'Bruno', 'Giacomelli', NULL, NULL, NULL, NULL),
	(311, NULL, NULL, 'Dick', 'Gibson', NULL, NULL, NULL, NULL),
(312, NULL, NULL, 'Richie', 'Ginther', NULL, NULL, NULL, NULL),
(313, NULL, NULL, 'Antonio', 'Giovinazzi', NULL, NULL, NULL, NULL),
(314, NULL, NULL, 'Yves', 'Giraud-Cabantous', NULL, NULL, NULL, NULL),
(315, NULL, NULL, 'Ignazio', 'Giunti', NULL, NULL, NULL, NULL),
(316, NULL, NULL, 'Timo', 'Glock', NULL, NULL, NULL, NULL),
(317, NULL, NULL, 'Helm', 'Glöckler', NULL, NULL, NULL, NULL),
(318, NULL, NULL, 'Paco', 'Godia', NULL, NULL, NULL, NULL),
(319, NULL, NULL, 'Carel', 'Godin', NULL, NULL, NULL, NULL),
(320, NULL, NULL, 'Christian', 'Goethals', NULL, NULL, NULL, NULL),
(321, NULL, NULL, 'Paul', 'Goldsmith', NULL, NULL, NULL, NULL),
(322, NULL, NULL, 'José Froilán', 'González', NULL, NULL, NULL, NULL),
(323, NULL, NULL, 'Óscar', 'González', NULL, NULL, NULL, NULL),
(324, NULL, NULL, 'Aldo', 'Gordini', NULL, NULL, NULL, NULL),
(325, NULL, NULL, 'Horace', 'Gould', NULL, NULL, NULL, NULL),
(326, NULL, NULL, 'Jean-Marc', 'Gounon', NULL, NULL, NULL, NULL),
(327, NULL, NULL, 'Emmanuel de', 'Graffenried', NULL, NULL, NULL, NULL),
(328, NULL, NULL, 'Lucas di', 'Grassi', NULL, NULL, NULL, NULL),
(329, NULL, NULL, 'Cecil', 'Green', NULL, NULL, NULL, NULL),
(330, NULL, NULL, 'Keith', 'Greene', NULL, NULL, NULL, NULL),
(331, NULL, NULL, 'Masten', 'Gregory', NULL, NULL, NULL, NULL),
(332, NULL, NULL, 'Cliff', 'Griffith', NULL, NULL, NULL, NULL),
(333, NULL, NULL, 'Georges', 'Grignard', NULL, NULL, NULL, NULL),
(334, NULL, NULL, 'Bobby', 'Grim', NULL, NULL, NULL, NULL),
(335, NULL, NULL, 'Romain', 'Grosjean', NULL, NULL, NULL, NULL),
(336, NULL, NULL, 'Olivier', 'Grouillard', NULL, NULL, NULL, NULL),
(337, NULL, NULL, 'Brian', 'Gubby', NULL, NULL, NULL, NULL),
(338, NULL, NULL, 'André', 'Guelfi', NULL, NULL, NULL, NULL),
(339, NULL, NULL, 'Miguel Ángel', 'Guerra', NULL, NULL, NULL, NULL),
(340, NULL, NULL, 'Roberto', 'Guerrero', NULL, NULL, NULL, NULL),
(341, NULL, NULL, 'Maurício', 'Gugelmin', NULL, NULL, NULL, NULL),
(342, NULL, NULL, 'Dan', 'Gurney', NULL, NULL, NULL, NULL),
(343, NULL, NULL, 'Esteban', 'Gutiérrez', NULL, NULL, NULL, NULL),
(344, NULL, NULL, 'Oscar Alfredo', 'Gálvez', NULL, NULL, NULL, NULL),
(345, NULL, NULL, 'Hubert', 'Hahne', NULL, NULL, NULL, NULL),
(346, NULL, NULL, 'Mike', 'Hailwood', NULL, NULL, NULL, NULL),
(347, NULL, NULL, 'Bruce', 'Halford', NULL, NULL, NULL, NULL),
(348, NULL, NULL, 'Jim', 'Hall', NULL, NULL, NULL, NULL),
(349, NULL, NULL, 'Duncan', 'Hamilton', NULL, NULL, NULL, NULL),
(350, NULL, NULL, 'David', 'Hampshire', NULL, NULL, NULL, NULL),
(351, NULL, NULL, 'Sam', 'Hanks', NULL, NULL, NULL, NULL),
(352, NULL, NULL, 'Walt', 'Hansgen', NULL, NULL, NULL, NULL),
(353, NULL, NULL, 'Mike', 'Harris', NULL, NULL, NULL, NULL),
(354, NULL, NULL, 'Cuth', 'Harrison', NULL, NULL, NULL, NULL),
(355, NULL, NULL, 'Brian', 'Hart', NULL, NULL, NULL, NULL),
(356, NULL, NULL, 'Brendon', 'Hartley', NULL, NULL, NULL, NULL),
(357, NULL, NULL, 'Gene', 'Hartley', NULL, NULL, NULL, NULL),
(358, NULL, NULL, 'Rio', 'Haryanto', NULL, NULL, NULL, NULL),
(359, NULL, NULL, 'Masahiro', 'Hasemi', NULL, NULL, NULL, NULL),
(360, NULL, NULL, 'Naoki', 'Hattori', NULL, NULL, NULL, NULL),
(361, NULL, NULL, 'Paul', 'Hawkins', NULL, NULL, NULL, NULL),
(362, NULL, NULL, 'Mike', 'Hawthorn', NULL, NULL, NULL, NULL),
(363, NULL, NULL, 'Boy', 'Hayje', NULL, NULL, NULL, NULL),
(364, NULL, NULL, 'Willi', 'Heeks', NULL, NULL, NULL, NULL),
(365, NULL, NULL, 'Nick', 'Heidfeld', NULL, NULL, NULL, NULL),
(366, NULL, NULL, 'Theo', 'Helfrich', NULL, NULL, NULL, NULL),
(367, NULL, NULL, 'Mack', 'Hellings', NULL, NULL, NULL, NULL),
(368, NULL, NULL, 'Brian', 'Henton', NULL, NULL, NULL, NULL),
(369, NULL, NULL, 'Johnny', 'Herbert', NULL, NULL, NULL, NULL),
(370, NULL, NULL, 'Al', 'Herman', NULL, NULL, NULL, NULL),
(371, NULL, NULL, 'Hans', 'Herrmann', NULL, NULL, NULL, NULL),
(372, NULL, NULL, 'François', 'Hesnault', NULL, NULL, NULL, NULL),
(373, NULL, NULL, 'Hans', 'Heyer', NULL, NULL, NULL, NULL),
(374, NULL, NULL, 'Damon', 'Hill', NULL, NULL, NULL, NULL),
(375, NULL, NULL, 'Graham', 'Hill', NULL, NULL, NULL, NULL),
(376, NULL, NULL, 'Phil', 'Hill', NULL, NULL, NULL, NULL),
(377, NULL, NULL, 'Peter', 'Hirt', NULL, NULL, NULL, NULL),
(378, NULL, NULL, 'David', 'Hobbs', NULL, NULL, NULL, NULL),
(379, NULL, NULL, 'Gary', 'Hocking', NULL, NULL, NULL, NULL),
(380, NULL, NULL, 'Ingo', 'Hoffmann', NULL, NULL, NULL, NULL),
(381, NULL, NULL, 'Bill', 'Holland', NULL, NULL, NULL, NULL),
(382, NULL, NULL, 'Jackie', 'Holmes', NULL, NULL, NULL, NULL),
(383, NULL, NULL, 'Bill', 'Homeier', NULL, NULL, NULL, NULL),
(384, NULL, NULL, 'Kazuyoshi', 'Hoshino', NULL, NULL, NULL, NULL),
(385, NULL, NULL, 'Jerry', 'Hoyt', NULL, NULL, NULL, NULL),
(386, NULL, NULL, 'Denny', 'Hulme', NULL, NULL, NULL, NULL),
(387, NULL, NULL, 'James', 'Hunt', NULL, NULL, NULL, NULL),
(388, NULL, NULL, 'Jim', 'Hurtubise', NULL, NULL, NULL, NULL),
(389, NULL, NULL, 'Gus', 'Hutchison', NULL, NULL, NULL, NULL),
(390, NULL, NULL, 'Mika', 'Häkkinen', NULL, NULL, NULL, NULL),
(391, NULL, NULL, 'Jacky', 'Ickx', NULL, NULL, NULL, NULL),
(392, NULL, NULL, 'Yuji', 'Ide', NULL, NULL, NULL, NULL),
(393, NULL, NULL, 'Jesús', 'Iglesias', NULL, NULL, NULL, NULL),
(394, NULL, NULL, 'Taki', 'Inoue', NULL, NULL, NULL, NULL),
(395, NULL, NULL, 'Innes', 'Ireland', NULL, NULL, NULL, NULL),
(396, NULL, NULL, 'Eddie', 'Irvine', NULL, NULL, NULL, NULL),
(397, NULL, NULL, 'Chris', 'Irwin', NULL, NULL, NULL, NULL),
(398, NULL, NULL, 'Jean-Pierre', 'Jabouille', NULL, NULL, NULL, NULL),
(399, NULL, NULL, 'Jimmy', 'Jackson', NULL, NULL, NULL, NULL),
(400, NULL, NULL, 'Joe', 'James', NULL, NULL, NULL, NULL),
(401, NULL, NULL, 'John', 'James', NULL, NULL, NULL, NULL),
(402, NULL, NULL, 'Jean-Pierre', 'Jarier', NULL, NULL, NULL, NULL),
(403, NULL, NULL, 'Max', 'Jean', NULL, NULL, NULL, NULL),
(404, NULL, NULL, 'Stefan', 'Johansson', NULL, NULL, NULL, NULL),
(405, NULL, NULL, 'Eddie', 'Johnson', NULL, NULL, NULL, NULL),
(406, NULL, NULL, 'Leslie', 'Johnson', NULL, NULL, NULL, NULL),
(407, NULL, NULL, 'Bruce', 'Johnstone', NULL, NULL, NULL, NULL),
(408, NULL, NULL, 'Alan', 'Jones', NULL, NULL, NULL, NULL),
(409, NULL, NULL, 'Tom', 'Jones', NULL, NULL, NULL, NULL),
(410, NULL, NULL, 'Juan', 'Jover', NULL, NULL, NULL, NULL),
(411, NULL, NULL, 'Oswald', 'Karch', NULL, NULL, NULL, NULL),
(412, NULL, NULL, 'Narain', 'Karthikeyan', NULL, NULL, NULL, NULL),
(413, NULL, NULL, 'Ukyo', 'Katayama', NULL, NULL, NULL, NULL),
(414, NULL, NULL, 'Ken', 'Kavanagh', NULL, NULL, NULL, NULL),
(415, NULL, NULL, 'Rupert', 'Keegan', NULL, NULL, NULL, NULL),
(416, NULL, NULL, 'Eddie', 'Keizan', NULL, NULL, NULL, NULL),
(417, NULL, NULL, 'Al', 'Keller', NULL, NULL, NULL, NULL),
(418, NULL, NULL, 'Joe', 'Kelly', NULL, NULL, NULL, NULL),
(419, NULL, NULL, 'David', 'Kennedy', NULL, NULL, NULL, NULL),
(420, NULL, NULL, 'Loris', 'Kessel', NULL, NULL, NULL, NULL),
(421, NULL, NULL, 'Bruce', 'Kessler', NULL, NULL, NULL, NULL),
(422, NULL, NULL, 'Nicolas', 'Kiesa', NULL, NULL, NULL, NULL),
(423, NULL, NULL, 'Leo', 'Kinnunen', NULL, NULL, NULL, NULL),
(424, NULL, NULL, 'Danny', 'Kladis', NULL, NULL, NULL, NULL),
(425, NULL, NULL, 'Hans', 'Klenk', NULL, NULL, NULL, NULL),
(426, NULL, NULL, 'Peter de', 'Klerk', NULL, NULL, NULL, NULL),
(427, NULL, NULL, 'Christian', 'Klien', NULL, NULL, NULL, NULL),
(428, NULL, NULL, 'Karl', 'Kling', NULL, NULL, NULL, NULL),
(429, NULL, NULL, 'Ernst', 'Klodwig', NULL, NULL, NULL, NULL),
(430, NULL, NULL, 'Kamui', 'Kobayashi', NULL, NULL, NULL, NULL),
(431, NULL, NULL, 'Helmuth', 'Koinigg', NULL, NULL, NULL, NULL),
(432, NULL, NULL, 'Heikki', 'Kovalainen', NULL, NULL, NULL, NULL),
(433, NULL, NULL, 'Mikko', 'Kozarowitzky', NULL, NULL, NULL, NULL),
(434, NULL, NULL, 'Willi', 'Krakau', NULL, NULL, NULL, NULL),
(435, NULL, NULL, 'Rudolf', 'Krause', NULL, NULL, NULL, NULL),
(436, NULL, NULL, 'Robert', 'Kubica', NULL, NULL, NULL, NULL),
(437, NULL, NULL, 'Kurt', 'Kuhnke', NULL, NULL, NULL, NULL),
(438, NULL, NULL, 'Masami', 'Kuwashima', NULL, NULL, NULL, NULL),
(439, NULL, NULL, 'Daniil', 'Kvyat', NULL, NULL, NULL, NULL),
(440, NULL, NULL, 'Robert', 'La Caze', NULL, NULL, NULL, NULL),
(441, NULL, NULL, 'Jacques', 'Laffite', NULL, NULL, NULL, NULL),
(442, NULL, NULL, 'Franck', 'Lagorce', NULL, NULL, NULL, NULL),
(443, NULL, NULL, 'Jan', 'Lammers', NULL, NULL, NULL, NULL),
(444, NULL, NULL, 'Pedro', 'Lamy', NULL, NULL, NULL, NULL),
(445, NULL, NULL, 'Chico', 'Landi', NULL, NULL, NULL, NULL),
(446, NULL, NULL, 'Hermann', 'Lang', NULL, NULL, NULL, NULL),
(447, NULL, NULL, 'Claudio', 'Langes', NULL, NULL, NULL, NULL),
(448, NULL, NULL, 'Nicola', 'Larini', NULL, NULL, NULL, NULL),
(449, NULL, NULL, 'Oscar', 'Larrauri', NULL, NULL, NULL, NULL),
(450, NULL, NULL, 'Gérard', 'Larrousse', NULL, NULL, NULL, NULL),
(451, NULL, NULL, 'Jud', 'Larson', NULL, NULL, NULL, NULL),
(452, NULL, NULL, 'Niki', 'Lauda', NULL, NULL, NULL, NULL),
(453, NULL, NULL, 'Roger', 'Laurent', NULL, NULL, NULL, NULL),
(454, NULL, NULL, 'Giovanni', 'Lavaggi', NULL, NULL, NULL, NULL),
(455, NULL, NULL, 'Chris', 'Lawrence', NULL, NULL, NULL, NULL),
(456, NULL, NULL, 'Michel', 'Leclère', NULL, NULL, NULL, NULL),
(457, NULL, NULL, 'Neville', 'Lederle', NULL, NULL, NULL, NULL),
(458, NULL, NULL, 'Geoff', 'Lees', NULL, NULL, NULL, NULL),
(459, NULL, NULL, 'Arthur', 'Legat', NULL, NULL, NULL, NULL),
(460, NULL, NULL, 'JJ', 'Lehto', NULL, NULL, NULL, NULL),
(461, NULL, NULL, 'Gijs van', 'Lennep', NULL, NULL, NULL, NULL),
(462, NULL, NULL, 'Lamberto', 'Leoni', NULL, NULL, NULL, NULL),
(463, NULL, NULL, 'Les', 'Leston', NULL, NULL, NULL, NULL),
(464, NULL, NULL, 'Pierre', 'Levegh', NULL, NULL, NULL, NULL),
(465, NULL, NULL, 'Bayliss', 'Levrett', NULL, NULL, NULL, NULL),
(466, NULL, NULL, 'Jackie', 'Lewis', NULL, NULL, NULL, NULL),
(467, NULL, NULL, 'Stuart', 'Lewis-Evans', NULL, NULL, NULL, NULL),
(468, NULL, NULL, 'Guy', 'Ligier', NULL, NULL, NULL, NULL),
(469, NULL, NULL, 'Andy', 'Linden', NULL, NULL, NULL, NULL),
(470, NULL, NULL, 'Roberto', 'Lippi', NULL, NULL, NULL, NULL),
(471, NULL, NULL, 'Vitantonio', 'Liuzzi', NULL, NULL, NULL, NULL),
(472, NULL, NULL, 'Dries van der', 'Lof', NULL, NULL, NULL, NULL),
(473, NULL, NULL, 'Lella', 'Lombardi', NULL, NULL, NULL, NULL),
(474, NULL, NULL, 'Ricardo', 'Londoño', NULL, NULL, NULL, NULL),
(475, NULL, NULL, 'Ernst', 'Loof', NULL, NULL, NULL, NULL),
(476, NULL, NULL, 'André', 'Lotterer', NULL, NULL, NULL, NULL),
(477, NULL, NULL, 'Henri', 'Louveau', NULL, NULL, NULL, NULL),
(478, NULL, NULL, 'John', 'Love', NULL, NULL, NULL, NULL),
(479, NULL, NULL, 'Pete', 'Lovely', NULL, NULL, NULL, NULL),
(480, NULL, NULL, 'Roger', 'Loyer', NULL, NULL, NULL, NULL),
(481, NULL, NULL, 'Jean', 'Lucas', NULL, NULL, NULL, NULL),
(482, NULL, NULL, 'Jean', 'Lucienbonnet', NULL, NULL, NULL, NULL),
(483, NULL, NULL, 'Brett', 'Lunger', NULL, NULL, NULL, NULL),
(484, NULL, NULL, 'Mike', 'MacDowel', NULL, NULL, NULL, NULL),
(485, NULL, NULL, 'Herbert', 'MacKay-Fraser', NULL, NULL, NULL, NULL),
(486, NULL, NULL, 'Bill', 'Mackey', NULL, NULL, NULL, NULL),
(487, NULL, NULL, 'Lance', 'Macklin', NULL, NULL, NULL, NULL),
(488, NULL, NULL, 'Damien', 'Magee', NULL, NULL, NULL, NULL),
(489, NULL, NULL, 'Tony', 'Maggs', NULL, NULL, NULL, NULL),
(490, NULL, NULL, 'Mike', 'Magill', NULL, NULL, NULL, NULL),
(491, NULL, NULL, 'Umberto', 'Maglioli', NULL, NULL, NULL, NULL),
(492, NULL, NULL, 'Jan', 'Magnussen', NULL, NULL, NULL, NULL),
(493, NULL, NULL, 'Guy', 'Mairesse', NULL, NULL, NULL, NULL),
(494, NULL, NULL, 'Willy', 'Mairesse', NULL, NULL, NULL, NULL),
(495, NULL, NULL, 'Pastor', 'Maldonado', NULL, NULL, NULL, NULL),
(496, NULL, NULL, 'Nigel', 'Mansell', NULL, NULL, NULL, NULL),
(497, NULL, NULL, 'Sergio', 'Mantovani', NULL, NULL, NULL, NULL),
(498, NULL, NULL, 'Johnny', 'Mantz', NULL, NULL, NULL, NULL),
(499, NULL, NULL, 'Robert', 'Manzon', NULL, NULL, NULL, NULL),
(500, NULL, NULL, 'Onofre', 'Marimón', NULL, NULL, NULL, NULL),
(501, NULL, NULL, 'Helmut', 'Marko', NULL, NULL, NULL, NULL),
(502, NULL, NULL, 'Tarso', 'Marques', NULL, NULL, NULL, NULL),
(503, NULL, NULL, 'Leslie', 'Marr', NULL, NULL, NULL, NULL),
(504, NULL, NULL, 'Tony', 'Marsh', NULL, NULL, NULL, NULL),
(505, NULL, NULL, 'Eugène', 'Martin', NULL, NULL, NULL, NULL),
(506, NULL, NULL, 'Pierluigi', 'Martini', NULL, NULL, NULL, NULL),
(507, NULL, NULL, 'Jochen', 'Mass', NULL, NULL, NULL, NULL),
(508, NULL, NULL, 'Felipe', 'Massa', NULL, NULL, NULL, NULL),
(509, NULL, NULL, 'Cristiano da', 'Matta', NULL, NULL, NULL, NULL),
(510, NULL, NULL, 'Michael', 'May', NULL, NULL, NULL, NULL),
	(511, NULL, NULL, 'Timmy', 'Mayer', NULL, NULL, NULL, NULL),
(512, NULL, NULL, 'François', 'Mazet', NULL, NULL, NULL, NULL),
(513, NULL, NULL, 'Gastón', 'Mazzacane', NULL, NULL, NULL, NULL),
(514, NULL, NULL, 'Kenneth', 'McAlpine', NULL, NULL, NULL, NULL),
(515, NULL, NULL, 'Perry', 'McCarthy', NULL, NULL, NULL, NULL),
(516, NULL, NULL, 'Ernie', 'McCoy', NULL, NULL, NULL, NULL),
(517, NULL, NULL, 'Johnny', 'McDowell', NULL, NULL, NULL, NULL),
(518, NULL, NULL, 'Jack', 'McGrath', NULL, NULL, NULL, NULL),
(519, NULL, NULL, 'Brian', 'McGuire', NULL, NULL, NULL, NULL),
(520, NULL, NULL, 'Bruce', 'McLaren', NULL, NULL, NULL, NULL),
(521, NULL, NULL, 'Allan', 'McNish', NULL, NULL, NULL, NULL),
(522, NULL, NULL, 'Graham', 'McRae', NULL, NULL, NULL, NULL),
(523, NULL, NULL, 'Jim', 'McWithey', NULL, NULL, NULL, NULL),
(524, NULL, NULL, 'Carlos', 'Menditeguy', NULL, NULL, NULL, NULL),
(525, NULL, NULL, 'Roberto', 'Merhi', NULL, NULL, NULL, NULL),
(526, NULL, NULL, 'Harry', 'Merkel', NULL, NULL, NULL, NULL),
(527, NULL, NULL, 'Arturo', 'Merzario', NULL, NULL, NULL, NULL),
(528, NULL, NULL, 'Roberto', 'Mieres', NULL, NULL, NULL, NULL),
(529, NULL, NULL, 'François', 'Migault', NULL, NULL, NULL, NULL),
(530, NULL, NULL, 'John', 'Miles', NULL, NULL, NULL, NULL),
(531, NULL, NULL, 'Ken', 'Miles', NULL, NULL, NULL, NULL),
(532, NULL, NULL, 'André', 'Milhoux', NULL, NULL, NULL, NULL),
(533, NULL, NULL, 'Chet', 'Miller', NULL, NULL, NULL, NULL),
(534, NULL, NULL, 'Gerhard', 'Mitter', NULL, NULL, NULL, NULL),
(535, NULL, NULL, 'Stefano', 'Modena', NULL, NULL, NULL, NULL),
(536, NULL, NULL, 'Thomas', 'Monarch', NULL, NULL, NULL, NULL),
(537, NULL, NULL, 'Franck', 'Montagny', NULL, NULL, NULL, NULL),
(538, NULL, NULL, 'Tiago', 'Monteiro', NULL, NULL, NULL, NULL),
(539, NULL, NULL, 'Andrea', 'Montermini', NULL, NULL, NULL, NULL),
(540, NULL, NULL, 'Peter', 'Monteverdi', NULL, NULL, NULL, NULL),
(541, NULL, NULL, 'Robin', 'Montgomerie-Charrington', NULL, NULL, NULL, NULL),
(542, NULL, NULL, 'Juan Pablo', 'Montoya', NULL, NULL, NULL, NULL),
(543, NULL, NULL, 'Gianni', 'Morbidelli', NULL, NULL, NULL, NULL),
(544, NULL, NULL, 'Roberto', 'Moreno', NULL, NULL, NULL, NULL),
(545, NULL, NULL, 'Dave', 'Morgan', NULL, NULL, NULL, NULL),
(546, NULL, NULL, 'Silvio', 'Moser', NULL, NULL, NULL, NULL),
(547, NULL, NULL, 'Bill', 'Moss', NULL, NULL, NULL, NULL),
(548, NULL, NULL, 'Stirling', 'Moss', NULL, NULL, NULL, NULL),
(549, NULL, NULL, 'Gino', 'Munaron', NULL, NULL, NULL, NULL),
(550, NULL, NULL, 'David', 'Murray', NULL, NULL, NULL, NULL),
(551, NULL, NULL, 'Luigi', 'Musso', NULL, NULL, NULL, NULL),
(552, NULL, NULL, 'Kazuki', 'Nakajima', NULL, NULL, NULL, NULL),
(553, NULL, NULL, 'Satoru', 'Nakajima', NULL, NULL, NULL, NULL),
(554, NULL, NULL, 'Shinji', 'Nakano', NULL, NULL, NULL, NULL),
(555, NULL, NULL, 'Duke', 'Nalon', NULL, NULL, NULL, NULL),
(556, NULL, NULL, 'Alessandro', 'Nannini', NULL, NULL, NULL, NULL),
(557, NULL, NULL, 'Emanuele', 'Naspetti', NULL, NULL, NULL, NULL),
(558, NULL, NULL, 'Felipe', 'Nasr', NULL, NULL, NULL, NULL),
(559, NULL, NULL, 'Massimo', 'Natili', NULL, NULL, NULL, NULL),
(560, NULL, NULL, 'Brian', 'Naylor', NULL, NULL, NULL, NULL),
(561, NULL, NULL, 'Mike', 'Nazaruk', NULL, NULL, NULL, NULL),
(562, NULL, NULL, 'Tiff', 'Needell', NULL, NULL, NULL, NULL),
(563, NULL, NULL, 'Jac', 'Nellemann', NULL, NULL, NULL, NULL),
(564, NULL, NULL, 'John', 'Nicholson', NULL, NULL, NULL, NULL),
(565, NULL, NULL, 'Cal', 'Niday', NULL, NULL, NULL, NULL),
(566, NULL, NULL, 'Helmut', 'Niedermayr', NULL, NULL, NULL, NULL),
(567, NULL, NULL, 'Brausch', 'Niemann', NULL, NULL, NULL, NULL),
(568, NULL, NULL, 'Gunnar', 'Nilsson', NULL, NULL, NULL, NULL),
(569, NULL, NULL, 'Hideki', 'Noda', NULL, NULL, NULL, NULL),
(570, NULL, NULL, 'Rodney', 'Nuckey', NULL, NULL, NULL, NULL),
(571, NULL, NULL, 'Patrick', 'Nève', NULL, NULL, NULL, NULL),
(572, NULL, NULL, 'Robert', 'O Brien', NULL, NULL, NULL, NULL),
(573, NULL, NULL, 'Pat', 'O Connor', NULL, NULL, NULL, NULL),
(574, NULL, NULL, 'Casimiro de', 'Oliveira', NULL, NULL, NULL, NULL),
(575, NULL, NULL, 'Jackie', 'Oliver', NULL, NULL, NULL, NULL),
(576, NULL, NULL, 'Danny', 'Ongais', NULL, NULL, NULL, NULL),
(577, NULL, NULL, 'Rikky von', 'Opel', NULL, NULL, NULL, NULL),
(578, NULL, NULL, 'Karl', 'Oppitzhauser', NULL, NULL, NULL, NULL),
(579, NULL, NULL, 'Fritz', 'd Orey', NULL, NULL, NULL, NULL),
(580, NULL, NULL, 'Arthur', 'Owen', NULL, NULL, NULL, NULL),
(581, NULL, NULL, 'Carlos', 'Pace', NULL, NULL, NULL, NULL),
(582, NULL, NULL, 'Nello', 'Pagani', NULL, NULL, NULL, NULL),
(583, NULL, NULL, 'Riccardo', 'Paletti', NULL, NULL, NULL, NULL),
(584, NULL, NULL, 'Torsten', 'Palm', NULL, NULL, NULL, NULL),
(585, NULL, NULL, 'Jolyon', 'Palmer', NULL, NULL, NULL, NULL),
(586, NULL, NULL, 'Jonathan', 'Palmer', NULL, NULL, NULL, NULL),
(587, NULL, NULL, 'Olivier', 'Panis', NULL, NULL, NULL, NULL),
(588, NULL, NULL, 'Giorgio', 'Pantano', NULL, NULL, NULL, NULL),
(589, NULL, NULL, 'Max', 'Papis', NULL, NULL, NULL, NULL),
(590, NULL, NULL, 'Mike', 'Parkes', NULL, NULL, NULL, NULL),
(591, NULL, NULL, 'Reg', 'Parnell', NULL, NULL, NULL, NULL),
(592, NULL, NULL, 'Tim', 'Parnell', NULL, NULL, NULL, NULL),
(593, NULL, NULL, 'Johnnie', 'Parsons', NULL, NULL, NULL, NULL),
(594, NULL, NULL, 'Riccardo', 'Patrese', NULL, NULL, NULL, NULL),
(595, NULL, NULL, 'Al', 'Pease', NULL, NULL, NULL, NULL),
(596, NULL, NULL, 'Roger', 'Penske', NULL, NULL, NULL, NULL),
(597, NULL, NULL, 'Cesare', 'Perdisa', NULL, NULL, NULL, NULL),
(598, NULL, NULL, 'Larry', 'Perkins', NULL, NULL, NULL, NULL),
(599, NULL, NULL, 'Henri', 'Pescarolo', NULL, NULL, NULL, NULL),
(600, NULL, NULL, 'Alessandro', 'Pesenti-Rossi', NULL, NULL, NULL, NULL),
(601, NULL, NULL, 'Josef', 'Peters', NULL, NULL, NULL, NULL),
(602, NULL, NULL, 'Ronnie', 'Peterson', NULL, NULL, NULL, NULL),
(603, NULL, NULL, 'Vitaly', 'Petrov', NULL, NULL, NULL, NULL),
(604, NULL, NULL, 'François', 'Picard', NULL, NULL, NULL, NULL),
(605, NULL, NULL, 'Ernie', 'Pieterse', NULL, NULL, NULL, NULL),
(606, NULL, NULL, 'Paul', 'Pietsch', NULL, NULL, NULL, NULL),
(607, NULL, NULL, 'André', 'Pilette', NULL, NULL, NULL, NULL),
(608, NULL, NULL, 'Teddy', 'Pilette', NULL, NULL, NULL, NULL),
(609, NULL, NULL, 'Luigi', 'Piotti', NULL, NULL, NULL, NULL),
(610, NULL, NULL, 'David', 'Piper', NULL, NULL, NULL, NULL),
(611, NULL, NULL, 'Nelson', 'Piquet Jr.', NULL, NULL, NULL, NULL),
(612, NULL, NULL, 'Nelson', 'Piquet', NULL, NULL, NULL, NULL),
(613, NULL, NULL, 'Renato', 'Pirocchi', NULL, NULL, NULL, NULL),
(614, NULL, NULL, 'Didier', 'Pironi', NULL, NULL, NULL, NULL),
(615, NULL, NULL, 'Emanuele', 'Pirro', NULL, NULL, NULL, NULL),
(616, NULL, NULL, 'Antônio', 'Pizzonia', NULL, NULL, NULL, NULL),
(617, NULL, NULL, 'Alfredo', 'Pián', NULL, NULL, NULL, NULL),
(618, NULL, NULL, 'Eric van', 'de Poele', NULL, NULL, NULL, NULL),
(619, NULL, NULL, 'Jacques', 'Pollet', NULL, NULL, NULL, NULL),
(620, NULL, NULL, 'Ben', 'Pon', NULL, NULL, NULL, NULL),
(621, NULL, NULL, 'Dennis', 'Poore', NULL, NULL, NULL, NULL),
(622, NULL, NULL, 'Alfonso de', 'Portago', NULL, NULL, NULL, NULL),
(623, NULL, NULL, 'Sam', 'Posey', NULL, NULL, NULL, NULL),
(624, NULL, NULL, 'Charles', 'Pozzi', NULL, NULL, NULL, NULL),
(625, NULL, NULL, 'Jackie', 'Pretorius', NULL, NULL, NULL, NULL),
(626, NULL, NULL, 'Ernesto', 'Prinoth', NULL, NULL, NULL, NULL),
(627, NULL, NULL, 'David', 'Prophet', NULL, NULL, NULL, NULL),
(628, NULL, NULL, 'Alain', 'Prost', NULL, NULL, NULL, NULL),
(629, NULL, NULL, 'Tom', 'Pryce', NULL, NULL, NULL, NULL),
(630, NULL, NULL, 'David', 'Purley', NULL, NULL, NULL, NULL),
(631, NULL, NULL, 'Clive', 'Puzey', NULL, NULL, NULL, NULL),
(632, NULL, NULL, 'Luis', 'Pérez-Sala', NULL, NULL, NULL, NULL),
(633, NULL, NULL, 'Dieter', 'Quester', NULL, NULL, NULL, NULL),
(634, NULL, NULL, 'Ian', 'Raby', NULL, NULL, NULL, NULL),
(635, NULL, NULL, 'Bobby', 'Rahal', NULL, NULL, NULL, NULL),
(636, NULL, NULL, 'Kimi', 'Räikkönen', NULL, NULL, NULL, NULL),
(637, NULL, NULL, 'Hermano da', 'Silva Ramos', NULL, NULL, NULL, NULL),
(638, NULL, NULL, 'Pierre-Henri', 'Raphanel', NULL, NULL, NULL, NULL),
(639, NULL, NULL, 'Dick', 'Rathmann', NULL, NULL, NULL, NULL),
(640, NULL, NULL, 'Jim', 'Rathmann', NULL, NULL, NULL, NULL),
(641, NULL, NULL, 'Roland', 'Ratzenberger', NULL, NULL, NULL, NULL),
(642, NULL, NULL, 'Héctor', 'Rebaque', NULL, NULL, NULL, NULL),
(643, NULL, NULL, 'Brian', 'Redman', NULL, NULL, NULL, NULL),
(644, NULL, NULL, 'Jimmy', 'Reece', NULL, NULL, NULL, NULL),
(645, NULL, NULL, 'Ray', 'Reed', NULL, NULL, NULL, NULL),
(646, NULL, NULL, 'Alan', 'Rees', NULL, NULL, NULL, NULL),
(647, NULL, NULL, 'Clay', 'Regazzoni', NULL, NULL, NULL, NULL),
(648, NULL, NULL, 'Paul di', 'Resta', NULL, NULL, NULL, NULL),
(649, NULL, NULL, 'Carlos', 'Reutemann', NULL, NULL, NULL, NULL),
(650, NULL, NULL, 'Lance', 'Reventlow', NULL, NULL, NULL, NULL),
(651, NULL, NULL, 'Peter', 'Revson', NULL, NULL, NULL, NULL),
(652, NULL, NULL, 'John', 'Rhodes', NULL, NULL, NULL, NULL),
(653, NULL, NULL, 'Alex', 'Ribeiro', NULL, NULL, NULL, NULL),
(654, NULL, NULL, 'Ken', 'Richardson', NULL, NULL, NULL, NULL),
(655, NULL, NULL, 'Fritz', 'Riess', NULL, NULL, NULL, NULL),
(656, NULL, NULL, 'Jim', 'Rigsby', NULL, NULL, NULL, NULL),
(657, NULL, NULL, 'Jochen', 'Rindt', NULL, NULL, NULL, NULL),
(658, NULL, NULL, 'John', 'Riseley-Prichard', NULL, NULL, NULL, NULL),
(659, NULL, NULL, 'Giovanni de', 'Riu', NULL, NULL, NULL, NULL),
(660, NULL, NULL, 'Richard', 'Robarts', NULL, NULL, NULL, NULL),
(661, NULL, NULL, 'Alberto Rodriguez', 'Larreta', NULL, NULL, NULL, NULL),
(662, NULL, NULL, 'Pedro', 'Rodríguez', NULL, NULL, NULL, NULL),
(663, NULL, NULL, 'Ricardo', 'Rodríguez', NULL, NULL, NULL, NULL),
(664, NULL, NULL, 'Franco', 'Rol', NULL, NULL, NULL, NULL),
(665, NULL, NULL, 'Alan', 'Rollinson', NULL, NULL, NULL, NULL),
(666, NULL, NULL, 'Tony', 'Rolt', NULL, NULL, NULL, NULL),
(667, NULL, NULL, 'Bertil', 'Roos', NULL, NULL, NULL, NULL),
(668, NULL, NULL, 'Basil van', 'Rooyen', NULL, NULL, NULL, NULL),
(669, NULL, NULL, 'Pedro de', 'la Rosa', NULL, NULL, NULL, NULL),
(670, NULL, NULL, 'Keke', 'Rosberg', NULL, NULL, NULL, NULL),
(671, NULL, NULL, 'Nico', 'Rosberg', NULL, NULL, NULL, NULL),
(672, NULL, NULL, 'Mauri', 'Rose', NULL, NULL, NULL, NULL),
(673, NULL, NULL, 'Louis', 'Rosier', NULL, NULL, NULL, NULL),
(674, NULL, NULL, 'Ricardo', 'Rosset', NULL, NULL, NULL, NULL),
(675, NULL, NULL, 'Alexander', 'Rossi', NULL, NULL, NULL, NULL),
(676, NULL, NULL, 'Huub', 'Rothengatter', NULL, NULL, NULL, NULL),
(677, NULL, NULL, 'Lloyd', 'Ruby', NULL, NULL, NULL, NULL),
(678, NULL, NULL, 'Jean-Claude', 'Rudaz', NULL, NULL, NULL, NULL),
(679, NULL, NULL, 'Eddie', 'Russo', NULL, NULL, NULL, NULL),
(680, NULL, NULL, 'Paul', 'Russo', NULL, NULL, NULL, NULL),
(681, NULL, NULL, 'Troy', 'Ruttman', NULL, NULL, NULL, NULL),
(682, NULL, NULL, 'Peter', 'Ryan', NULL, NULL, NULL, NULL),
(683, NULL, NULL, 'Eddie', 'Sachs', NULL, NULL, NULL, NULL),
(684, NULL, NULL, 'Bob', 'Said', NULL, NULL, NULL, NULL),
(685, NULL, NULL, 'Eliseo', 'Salazar', NULL, NULL, NULL, NULL),
(686, NULL, NULL, 'Mika', 'Salo', NULL, NULL, NULL, NULL),
(687, NULL, NULL, 'Roy', 'Salvadori', NULL, NULL, NULL, NULL),
(688, NULL, NULL, 'Consalvo', 'Sanesi', NULL, NULL, NULL, NULL),
(689, NULL, NULL, 'Stéphane', 'Sarrazin', NULL, NULL, NULL, NULL),
(690, NULL, NULL, 'Takuma', 'Sato', NULL, NULL, NULL, NULL),
(691, NULL, NULL, 'Carl', 'Scarborough', NULL, NULL, NULL, NULL),
(692, NULL, NULL, 'Ludovico', 'Scarfiotti', NULL, NULL, NULL, NULL),
(693, NULL, NULL, 'Giorgio', 'Scarlatti', NULL, NULL, NULL, NULL),
(694, NULL, NULL, 'Ian', 'Scheckter', NULL, NULL, NULL, NULL),
(695, NULL, NULL, 'Jody', 'Scheckter', NULL, NULL, NULL, NULL),
(696, NULL, NULL, 'Harry', 'Schell', NULL, NULL, NULL, NULL),
(697, NULL, NULL, 'Tim', 'Schenken', NULL, NULL, NULL, NULL),
(698, NULL, NULL, 'Albert', 'Scherrer', NULL, NULL, NULL, NULL),
(699, NULL, NULL, 'Domenico', 'Schiattarella', NULL, NULL, NULL, NULL),
(700, NULL, NULL, 'Heinz', 'Schiller', NULL, NULL, NULL, NULL),
	(701, NULL, NULL, 'Bill', 'Schindler', NULL, NULL, NULL, NULL),
(702, NULL, NULL, 'Jean-Louis', 'Schlesser', NULL, NULL, NULL, NULL),
(703, NULL, NULL, 'Jo', 'Schlesser', NULL, NULL, NULL, NULL),
(704, NULL, NULL, 'Bernd', 'Schneider', NULL, NULL, NULL, NULL),
(705, NULL, NULL, 'Rudolf', 'Schoeller', NULL, NULL, NULL, NULL),
(706, NULL, NULL, 'Rob', 'Schroeder', NULL, NULL, NULL, NULL),
(707, NULL, NULL, 'Michael', 'Schumacher', NULL, NULL, NULL, NULL),
(708, NULL, NULL, 'Ralf', 'Schumacher', NULL, NULL, NULL, NULL),
(709, NULL, NULL, 'Vern', 'Schuppan', NULL, NULL, NULL, NULL),
(710, NULL, NULL, 'Adolfo Schwelm', 'Cruz', NULL, NULL, NULL, NULL),
(711, NULL, NULL, 'Archie Scott', 'Brown', NULL, NULL, NULL, NULL),
(712, NULL, NULL, 'Bob', 'Scott', NULL, NULL, NULL, NULL),
(713, NULL, NULL, 'Piero', 'Scotti', NULL, NULL, NULL, NULL),
(714, NULL, NULL, 'Wolfgang', 'Seidel', NULL, NULL, NULL, NULL),
(715, NULL, NULL, 'Günther', 'Seiffert', NULL, NULL, NULL, NULL),
(716, NULL, NULL, 'Ayrton', 'Senna', NULL, NULL, NULL, NULL),
(717, NULL, NULL, 'Bruno', 'Senna', NULL, NULL, NULL, NULL),
(718, NULL, NULL, 'Dorino', 'Serafini', NULL, NULL, NULL, NULL),
(719, NULL, NULL, 'Chico', 'Serra', NULL, NULL, NULL, NULL),
(720, NULL, NULL, 'Doug', 'Serrurier', NULL, NULL, NULL, NULL),
(721, NULL, NULL, 'Johnny', 'Servoz-Gavin', NULL, NULL, NULL, NULL),
(722, NULL, NULL, 'Tony', 'Settember', NULL, NULL, NULL, NULL),
(723, NULL, NULL, 'Hap', 'Sharp', NULL, NULL, NULL, NULL),
(724, NULL, NULL, 'Brian', 'Shawe-Taylor', NULL, NULL, NULL, NULL),
(725, NULL, NULL, 'Carroll', 'Shelby', NULL, NULL, NULL, NULL),
(726, NULL, NULL, 'Tony', 'Shelly', NULL, NULL, NULL, NULL),
(727, NULL, NULL, 'Jo', 'Siffert', NULL, NULL, NULL, NULL),
(728, NULL, NULL, 'André', 'Simon', NULL, NULL, NULL, NULL),
(729, NULL, NULL, 'Rob', 'Slotemaker', NULL, NULL, NULL, NULL),
(730, NULL, NULL, 'Moisés', 'Solana', NULL, NULL, NULL, NULL),
(731, NULL, NULL, 'Alex', 'Soler-Roig', NULL, NULL, NULL, NULL),
(732, NULL, NULL, 'Raymond', 'Sommer', NULL, NULL, NULL, NULL),
(733, NULL, NULL, 'Vincenzo', 'Sospiri', NULL, NULL, NULL, NULL),
(734, NULL, NULL, 'Stephen', 'South', NULL, NULL, NULL, NULL),
(735, NULL, NULL, 'Mike', 'Sparken', NULL, NULL, NULL, NULL),
(736, NULL, NULL, 'Scott', 'Speed', NULL, NULL, NULL, NULL),
(737, NULL, NULL, 'Mike', 'Spence', NULL, NULL, NULL, NULL),
(738, NULL, NULL, 'Alan', 'Stacey', NULL, NULL, NULL, NULL),
(739, NULL, NULL, 'Gaetano', 'Starrabba', NULL, NULL, NULL, NULL),
(740, NULL, NULL, 'Will', 'Stevens', NULL, NULL, NULL, NULL),
(741, NULL, NULL, 'Chuck', 'Stevenson', NULL, NULL, NULL, NULL),
(742, NULL, NULL, 'Ian', 'Stewart', NULL, NULL, NULL, NULL),
(743, NULL, NULL, 'Jackie', 'Stewart', NULL, NULL, NULL, NULL),
(744, NULL, NULL, 'Jimmy', 'Stewart', NULL, NULL, NULL, NULL),
(745, NULL, NULL, 'Siegfried', 'Stohr', NULL, NULL, NULL, NULL),
(746, NULL, NULL, 'Rolf', 'Stommelen', NULL, NULL, NULL, NULL),
(747, NULL, NULL, 'Philippe', 'Streiff', NULL, NULL, NULL, NULL),
(748, NULL, NULL, 'Hans-Joachim', 'Stuck', NULL, NULL, NULL, NULL),
(749, NULL, NULL, 'Hans', 'Stuck', NULL, NULL, NULL, NULL),
(750, NULL, NULL, 'Otto', 'Stuppacher', NULL, NULL, NULL, NULL),
(751, NULL, NULL, 'Danny', 'Sullivan', NULL, NULL, NULL, NULL),
(752, NULL, NULL, 'Marc', 'Surer', NULL, NULL, NULL, NULL),
(753, NULL, NULL, 'John', 'Surtees', NULL, NULL, NULL, NULL),
(754, NULL, NULL, 'Andy', 'Sutcliffe', NULL, NULL, NULL, NULL),
(755, NULL, NULL, 'Adrian', 'Sutil', NULL, NULL, NULL, NULL),
(756, NULL, NULL, 'Len', 'Sutton', NULL, NULL, NULL, NULL),
(757, NULL, NULL, 'Aguri', 'Suzuki', NULL, NULL, NULL, NULL),
(758, NULL, NULL, 'Toshio', 'Suzuki', NULL, NULL, NULL, NULL),
(759, NULL, NULL, 'Jacques', 'Swaters', NULL, NULL, NULL, NULL),
(760, NULL, NULL, 'Bob', 'Sweikert', NULL, NULL, NULL, NULL),
(761, NULL, NULL, 'Toranosuke', 'Takagi', NULL, NULL, NULL, NULL),
(762, NULL, NULL, 'Noritake', 'Takahara', NULL, NULL, NULL, NULL),
(763, NULL, NULL, 'Kunimitsu', 'Takahashi', NULL, NULL, NULL, NULL),
(764, NULL, NULL, 'Patrick', 'Tambay', NULL, NULL, NULL, NULL),
(765, NULL, NULL, 'Luigi', 'Taramazzo', NULL, NULL, NULL, NULL),
(766, NULL, NULL, 'Gabriele', 'Tarquini', NULL, NULL, NULL, NULL),
(767, NULL, NULL, 'Piero', 'Taruffi', NULL, NULL, NULL, NULL),
(768, NULL, NULL, 'Dennis', 'Taylor', NULL, NULL, NULL, NULL),
(769, NULL, NULL, 'Henry', 'Taylor', NULL, NULL, NULL, NULL),
(770, NULL, NULL, 'John', 'Taylor', NULL, NULL, NULL, NULL),
(771, NULL, NULL, 'Mike', 'Taylor', NULL, NULL, NULL, NULL),
(772, NULL, NULL, 'Trevor', 'Taylor', NULL, NULL, NULL, NULL),
(773, NULL, NULL, 'Marshall', 'Teague', NULL, NULL, NULL, NULL),
(774, NULL, NULL, 'Shorty', 'Templeman', NULL, NULL, NULL, NULL),
(775, NULL, NULL, 'Max de', 'Terra', NULL, NULL, NULL, NULL),
(776, NULL, NULL, 'André', 'Testut', NULL, NULL, NULL, NULL),
(777, NULL, NULL, 'Mike', 'Thackwell', NULL, NULL, NULL, NULL),
(778, NULL, NULL, 'Alfonso', 'Thiele', NULL, NULL, NULL, NULL),
(779, NULL, NULL, 'Eric', 'Thompson', NULL, NULL, NULL, NULL),
(780, NULL, NULL, 'Johnny', 'Thomson', NULL, NULL, NULL, NULL),
(781, NULL, NULL, 'Leslie', 'Thorne', NULL, NULL, NULL, NULL),
(782, NULL, NULL, 'Bud', 'Tingelstad', NULL, NULL, NULL, NULL),
(783, NULL, NULL, 'Sam', 'Tingle', NULL, NULL, NULL, NULL),
(784, NULL, NULL, 'Desmond', 'Titterington', NULL, NULL, NULL, NULL),
	(785, NULL, NULL, 'Johnnie', 'Tolan', NULL, NULL, NULL, NULL),
(786, NULL, NULL, 'Alejandro de', 'Tomaso', NULL, NULL, NULL, NULL),
(787, NULL, NULL, 'Charles de', 'Tornaco', NULL, NULL, NULL, NULL),
(788, NULL, NULL, 'Tony', 'Trimmer', NULL, NULL, NULL, NULL),
(789, NULL, NULL, 'Maurice', 'Trintignant', NULL, NULL, NULL, NULL),
(790, NULL, NULL, 'Wolfgang von', 'Trips', NULL, NULL, NULL, NULL),
(791, NULL, NULL, 'Jarno', 'Trulli', NULL, NULL, NULL, NULL),
(792, NULL, NULL, 'Esteban', 'Tuero', NULL, NULL, NULL, NULL),
(793, NULL, NULL, 'Guy', 'Tunmer', NULL, NULL, NULL, NULL),
(794, NULL, NULL, 'Jack', 'Turner', NULL, NULL, NULL, NULL),
(795, NULL, NULL, 'Toni', 'Ulmen', NULL, NULL, NULL, NULL),
(796, NULL, NULL, 'Jerry', 'Unser Jr.', NULL, NULL, NULL, NULL),
(797, NULL, NULL, 'Bobby', 'Unser', NULL, NULL, NULL, NULL),
(798, NULL, NULL, 'Alberto', 'Uria', NULL, NULL, NULL, NULL),
(799, NULL, NULL, 'Nino', 'Vaccarella', NULL, NULL, NULL, NULL),
(800, NULL, NULL, 'Stoffel', 'Vandoorne', NULL, NULL, NULL, NULL),
	(801, NULL, NULL, 'Bob', 'Veith', NULL, NULL, NULL, NULL),
(802, NULL, NULL, 'Jean-Éric', 'Vergne', NULL, NULL, NULL, NULL),
(803, NULL, NULL, 'Jos', 'Verstappen', NULL, NULL, NULL, NULL),
(804, NULL, NULL, 'Sebastian', 'Vettel', NULL, NULL, NULL, NULL),
(805, NULL, NULL, 'Gilles', 'Villeneuve', NULL, NULL, NULL, NULL),
(806, NULL, NULL, 'Jacques', 'Villeneuve', NULL, NULL, NULL, NULL),
(807, NULL, NULL, 'Jacques', 'Villeneuve, Sr.', NULL, NULL, NULL, NULL),
(808, NULL, NULL, 'Luigi', 'Villoresi', NULL, NULL, NULL, NULL),
(809, NULL, NULL, 'Emilio de', 'Villota', NULL, NULL, NULL, NULL),
(810, NULL, NULL, 'Ottorino', 'Volonterio', NULL, NULL, NULL, NULL),
(811, NULL, NULL, 'Jo', 'Vonlanthen', NULL, NULL, NULL, NULL),
(812, NULL, NULL, 'Ernie de', 'Vos', NULL, NULL, NULL, NULL),
(813, NULL, NULL, 'Bill', 'Vukovich', NULL, NULL, NULL, NULL),
(814, NULL, NULL, 'Syd van der', 'Vyver', NULL, NULL, NULL, NULL),
(815, NULL, NULL, 'David', 'Walker', NULL, NULL, NULL, NULL),
(816, NULL, NULL, 'Peter', 'Walker', NULL, NULL, NULL, NULL),
(817, NULL, NULL, 'Lee', 'Wallard', NULL, NULL, NULL, NULL),
(818, NULL, NULL, 'Heini', 'Walter', NULL, NULL, NULL, NULL),
(819, NULL, NULL, 'Rodger', 'Ward', NULL, NULL, NULL, NULL),
(820, NULL, NULL, 'Derek', 'Warwick', NULL, NULL, NULL, NULL),
(821, NULL, NULL, 'John', 'Watson', NULL, NULL, NULL, NULL),
(822, NULL, NULL, 'Spider', 'Webb', NULL, NULL, NULL, NULL),
(823, NULL, NULL, 'Mark', 'Webber', NULL, NULL, NULL, NULL),
(824, NULL, NULL, 'Pascal', 'Wehrlein', NULL, NULL, NULL, NULL),
(825, NULL, NULL, 'Volker', 'Weidler', NULL, NULL, NULL, NULL),
(826, NULL, NULL, 'Wayne', 'Weiler', NULL, NULL, NULL, NULL),
(827, NULL, NULL, 'Karl', 'Wendlinger', NULL, NULL, NULL, NULL),
(828, NULL, NULL, 'Peter', 'Westbury', NULL, NULL, NULL, NULL),
(829, NULL, NULL, 'Chuck', 'Weyant', NULL, NULL, NULL, NULL),
(830, NULL, NULL, 'Ken', 'Wharton', NULL, NULL, NULL, NULL),
(831, NULL, NULL, 'Ted', 'Whiteaway', NULL, NULL, NULL, NULL),
(832, NULL, NULL, 'Graham', 'Whitehead', NULL, NULL, NULL, NULL),
(833, NULL, NULL, 'Peter', 'Whitehead', NULL, NULL, NULL, NULL),
(834, NULL, NULL, 'Bill', 'Whitehouse', NULL, NULL, NULL, NULL),
(835, NULL, NULL, 'Robin', 'Widdows', NULL, NULL, NULL, NULL),
(836, NULL, NULL, 'Eppie', 'Wietzes', NULL, NULL, NULL, NULL),
(837, NULL, NULL, 'Mike', 'Wilds', NULL, NULL, NULL, NULL),
(838, NULL, NULL, 'Jonathan', 'Williams', NULL, NULL, NULL, NULL),
(839, NULL, NULL, 'Roger', 'Williamson', NULL, NULL, NULL, NULL),
(840, NULL, NULL, 'Dempsey', 'Wilson', NULL, NULL, NULL, NULL),
(841, NULL, NULL, 'Desiré', 'Wilson', NULL, NULL, NULL, NULL),
(842, NULL, NULL, 'Justin', 'Wilson', NULL, NULL, NULL, NULL),
(843, NULL, NULL, 'Vic', 'Wilson', NULL, NULL, NULL, NULL),
(844, NULL, NULL, 'Joachim', 'Winkelhock', NULL, NULL, NULL, NULL),
(845, NULL, NULL, 'Manfred', 'Winkelhock', NULL, NULL, NULL, NULL),
(846, NULL, NULL, 'Markus', 'Winkelhock', NULL, NULL, NULL, NULL),
(847, NULL, NULL, 'Reine', 'Wisell', NULL, NULL, NULL, NULL),
(848, NULL, NULL, 'Roelof', 'Wunderink', NULL, NULL, NULL, NULL),
(849, NULL, NULL, 'Alexander', 'Wurz', NULL, NULL, NULL, NULL),
(850, NULL, NULL, 'Sakon', 'Yamamoto', NULL, NULL, NULL, NULL),
(851, NULL, NULL, 'Alex', 'Yoong', NULL, NULL, NULL, NULL),
(852, NULL, NULL, 'Alex', 'Zanardi', NULL, NULL, NULL, NULL),
(853, NULL, NULL, 'Emilio', 'Zapico', NULL, NULL, NULL, NULL),
(854, NULL, NULL, 'Ricardo', 'Zonta', NULL, NULL, NULL, NULL),
(855, NULL, NULL, 'Renzo', 'Zorzi', NULL, NULL, NULL, NULL),
(856, NULL, NULL, 'Ricardo', 'Zunino', NULL, NULL, NULL, NULL),
(857, NULL, NULL, 'Philippe', 'Étancelin', NULL, NULL, NULL, NULL);

-- select all info from table
SELECT * from drivers;

-- select all info from top 24 drivers
SELECT 
    d.DriverID, 
    d.firstName, 
    d.lastName, 
    d.dateOfBirth,
    d.born, 
    d.helmutColour, 
    d.number, 
	co.countryName
FROM drivers d
JOIN countries co ON d.CountryID = co.CountryID
ORDER BY d.DriverID 
OFFSET 0 ROWS
FETCH NEXT 24 ROWS ONLY;

-- select drivers in team by name and drivers last name
SELECT 
                d.DriverID,
                d.firstName,
                d.lastName,
                d.dateOfBirth,
                d.born,
                d.number,
                c.teamName
            FROM drivers d
            INNER JOIN constructors c ON d.TeamID = c.TeamID
            ORDER BY c.teamName, d.lastName;

UPDATE drivers
SET TeamID = (SELECT TeamID FROM constructors WHERE teamName = 'McLaren Formula 1 Team')
WHERE DriverID = 11;